server:
  port: 9999

spring:
  application:
    name: ttl-learn1

  rabbitmq:
    host: 192.168.18.131
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode #虚拟主机

my:
  exchangeName: exchange.ttl.a
  queueName: queue.ttl.a
