server:
  port: 9999

spring:
  application:
    name: return-learn1

  rabbitmq:
    host: 192.168.18.131
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode #虚拟主机
    publisher-confirm-type: correlated #开启生产者的确认模式，设置关联模式
    publisher-returns: true #开启交换机和队列的关联，并返回

my:
  exchangeName: exchange.return.1 #交换机
  queueName: queue.return.1 #正常队列
