server:
  port: 9999

spring:
  application:
    name: direct-exchange

  rabbitmq:
    host: 192.168.18.131
    port: 5672
    username: admin
    password: 123456
    virtual-host: powernode #虚拟主机

my:
  exchangeName: exchange.topic
  queueAName: queue.topic.a
  queueBName: queue.topic.b
